//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoProvaFortes
{
    using System;
    using System.Collections.Generic;

    public partial class tbItem
    {
        public int ID { get; set; }
        public string MATRICULA { get; set; }
        public string NUMERO { get; set; }
        public string NOME { get; set; }
        public string QUANTIDADE { get; set; }
        public string VALOR { get; set; }

        public tbItem()
        {
        }
        public tbItem(string mATRICULA, string nUMERO, string nOME, string qUANTIDADE, string vALOR)
        {
            MATRICULA = mATRICULA;
            NUMERO = nUMERO;
            NOME = nOME;
            QUANTIDADE = qUANTIDADE;
            VALOR = vALOR;
        }
    }
}
