//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoProvaFortes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNota
    {
        public int ID { get; set; }
        public string NUMERO { get; set; }
        public string DATA { get; set; }
        public string VALOR { get; set; }

        public tbNota()
        {

        }

        public tbNota(string nUMERO, string dATA, string vALOR)
        {
            NUMERO = nUMERO;
            DATA = dATA;
            VALOR = vALOR;
        }
    }
}
