//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoProvaFortes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTomador
    {
        public int ID { get; set; }
        public string CNPJ { get; set; }
        public string NOME { get; set; }
        public string RUA { get; set; }
        public string NUMERO { get; set; }
        public string BAIRRO { get; set; }
        public string UF { get; set; }
        public string TELEFONE { get; set; }
        public string EMAIL { get; set; }


        public tbTomador()
        {

        }
        public tbTomador(string cNPJ, string nOME, string rUA, string nUMERO, string bAIRRO, string uF, string tELEFONE, string eMAIL)
        {
            CNPJ = cNPJ;
            NOME = nOME;
            RUA = rUA;
            NUMERO = nUMERO;
            BAIRRO = bAIRRO;
            UF = uF;
            TELEFONE = tELEFONE;
            EMAIL = eMAIL;
        }
    }


}
